apiVersion: apps/v1
kind: Pod
metadata:
  name: hvnhi-nodeapp
spec:
  containers:
  - image: $IMAGE_NAME
    name: hvnhi-nodeapp
    ports:
    - containerPort: 5000
      hostPort: 5000
      protocol: TCP
