apiVersion: apps/v1
kind: Deployment
metadata:
  name: hvnhi-nodeapp
  labels:
    app: hvnhi-nodeapp
spec:
  replicas: 2
  strategy: # change here
    type: RollingUpdate # strategy type is Recreate or RollingUpdate. Default is RollingUpdate
  selector:
    matchLabels:
      app: hvnhi-nodeapp
  template:
    metadata:
      labels:
        app: hvnhi-nodeapp 
    spec:
      containers:
      - name: hvnhi-nodeapp
        image: $IMAGE_NAME
        imagePullPolicy: Always
        ports:
        - containerPort: 5000

---

apiVersion: apps/v1
kind: Service
metadata:
  name: hvnhi-nodeapp-service
spec:
  selector:
    app: hvnhi-nodeapp
  type: NodePort 
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000

--- 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hvnhi-nodeapp
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/whitelist-source-range: "171.244.18.3/32,103.200.23.9/32,118.69.63.53/32,103.90.226.251/32"
spec:
  tls:
  - hosts:
    - 14.225.254.202
    secretName: hvnhi-nodeapp
  rules:
  - host: 14.225.254.202
    http:
      paths:
      - backend:
          service:
            name: hvnhi-nodeapp-service
            port:
              number: 5000
        path: /
        pathType: Prefix