apiVersion: apps/v1
kind: Deployment
metadata:
  name: hvnhi-nodeapp
  labels:
    app: hvnhi-nodeapp
spec:
  replicas: 1
  strategy: # change here
    type: RollingUpdate # strategy type is Recreate or RollingUpdate. Default is RollingUpdate
  selector:
    matchLabels:
      app: hvnhi-nodeapp
  template:
    metadata:
      labels:
        app: hvnhi-nodeapp 
    spec:
      containers:
      - name: hvnhi-nodeapp
        image: hvnhi/nodeapp:v01
        imagePullSecrets:
        - name: docker-hub-token
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: hvnhi-nodeapp-service
spec:
  selector:
    app: hvnhi-nodeapp
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 32000
